model_path: /home/yw2692/workspace/Brain-MRI-Segmentation/mycode/3D-UNet/runs/exp3/best_checkpoint.pytorch

model:
  name: UNet3D
  in_channels: 1
  out_channels: 1
  layer_order: gcr
  f_maps: 16
  num_levels: 3
  num_groups: 8
  final_sigmoid: true

predictor:
  name: StandardPredictor

loaders:
  output_dir: /home/yw2692/3D-UNet/test_output_3  # all smoothing overlay
  batch_size: 1
  num_workers: 0  # to avoid memory overload

  test:
    file_paths:
      - /share/sablab/nfs04/data/Prostate-MRI-US-Biopsy/susan/hdf5_dataset/val  # or your test folder if separated

    slice_builder:
      name: SliceBuilder
      patch_shape: [20, 128, 128]       # match validation shape
      stride_shape: [10, 64, 64]      # no overlap during inference
      halo_shape: [4, 16, 16]        # optional smoothing across patch boundaries

    transformer:
      raw:
        - name: Normalize
        - name: ToTensor
          expand_dims: true